### ISSUE TITLE
`ap` examples

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/mostly-adequate-fp-ts#15]
Provide translations for the following:

```js
// Http.get :: String -> Task Error HTML

const renderPage = curry((destinations, events) => { /* render page */ });

Task.of(renderPage).ap(Http.get('/destinations')).ap(Http.get('/events'));
// Task("<div>some page with dest and events</div>")
```

```js
// $ :: String -> IO DOM
const $ = selector => new IO(() => document.querySelector(selector));

// getVal :: String -> IO String
const getVal = compose(map(prop('value')), $);

// signIn :: String -> String -> Bool -> User
const signIn = curry((username, password, rememberMe) => { /* signing in */ });

IO.of(signIn).ap(getVal('#email')).ap(getVal('#password')).ap(IO.of(false));
// IO({ id: 3, email: 'gg@allin.com' })
```

**Comment by ChuckJonas** [comment]
My attempt at the "renderPage" example.  A pain point that I keep running is dealing with `unknown` on the Left.  

I have to explicitly specify the `Right` type (which could be inferred) so I can tell it what the `Left` should be.  

```ts
// Http.get :: String -> Task Error HTML
const Http = {
  get: (url: string) => TE.of<Error, string>(`<div>${url}</div>`)
}

const renderPage = (destinations: string) => (events: string) => { return `<div>${destinations}${events}<div>`};

pipe(
  TE.of<Error, (destinations: string) => (events: string) => string>(renderPage),
  TE.ap(Http.get('/destinations')),
  TE.ap(Http.get('/events')),
)
// Task("<div>some page with dest and events</div>")
```

Wondering if there is a better way....

**Comment by ChuckJonas** [comment]
I guess I could do `TE.of<Error, typeof renderPage>(renderPage),` but still feels like boiler plate

**Comment by cdimitroulas** [comment]
I played around with this and found an option which doesn't require the extra type annotation, but I had to use `TE.right` instead of `TE.of` which might not be desirable since it's harder to see the equivalence with the book (even though `TE.right` is equivalent to `TE.of`).

I also declared the `Http` object in a way which doesn't have an implementation which feels a bit easier to follow as it clearly shows how `Http.get` can fail/succeed.

```ts
import * as TE from "fp-ts/lib/TaskEither";
import { pipe } from "fp-ts/lib/function";

declare const Http: {
  get: (url: string) => TE.TaskEither<Error, string>
}

const renderPage = (destinations: string) => (events: string) => {
  return `<div>${destinations}${events}<div>`;
};

pipe(
  TE.right(renderPage),
  TE.ap(Http.get("/destinations")),
  TE.ap(Http.get("/events"))
);
```

What do you think?

**Comment by ChuckJonas** [comment]
looks great! I think using `TE.right` is actually better because it exposes more of the library.  I will incorporate this change 👍

**Comment by cdimitroulas** [comment]
It's probably more idiomatic as well (for example at work we would always use `TE.right` rather than `TE.of` when needed)
