### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by gcanti** [ChuckJonas/mostly-adequate-fp-ts#2]
just a couple of suggestions:

- **imports**. prefer `import { map } from "fp-ts/Array";` over `import { map } from "fp-ts/lib/Array";` (`chapter-4.md`, `chapter-5.md`)
- **immutable data types**. prefer `import { map } from "fp-ts/ReadonlyArray";` over `import { map } from "fp-ts/Array";` (`chapter-4.md`)

**Comment by ChuckJonas** [comment]
awesome thank for the feedback!  

Any reason prefer "immutable data types" wouldn't also apply to the example using `Array.map` in CH5?

Seems like you would never actually need to mutate an array with FP.

**Comment by ChuckJonas** [comment]
I see that I would need to make the `intercalculate` as readonly.

```
const stringIntercalculate = (sep: string) => (s: readonly string[]) =>
  intercalate(S.Monoid, Foldable)(sep, s);
```

Do you tend to just put `readonly` on every signature?  Seems like a lot of additional boilerplate, but I guess the assurance against mutation is worth it.

**Comment by gcanti** [comment]
> Any reason prefer "immutable data types" wouldn't also apply to the example using Array.map in CH5?

ah I just missed it

> Seems like you would never actually need to mutate an array with FP.

:+1:

> Seems like a lot of additional boilerplate, but I guess the assurance against mutation is worth it.

Yeah, alas TypeScript isn't `readonly`-friedly

**Comment by ChuckJonas** [comment]
#10 created to deal with `ReadonlyArray` vs `Array`
