### ISSUE TITLE
Checklist of chapters/items to complete

### ISSUE THREAD

**Issue by cdimitroulas** [ChuckJonas/mostly-adequate-fp-ts#3]
First of all, I want to say thanks for this initiative! I think it will be very helpful to complete this guide for folks who are interested in using/learning fp-ts :smile: 

In order to allow others to contribute to this easily, it would be great to have visibility on what has been completed and what is already being worked on so that we don't duplicate efforts. Could we create a pinned issue with a checklist of these items?

For example, I see that chapters 1, 4, 5, 6 & 8 are already done (not sure if 100% complete, I didn't look at the files yet) but it's unclear if you or someone else is already working on the other chapters

**Comment by ChuckJonas** [comment]
Yea I had been thinking about this as well and I think we definitely need something.  I was actually thinking about breaking out individual code examples or at least subsections into issues as some chapters are quite long and that makes it easier for me to ask for help for specific concepts/features I don't yet understand.

In a pinned issue, we could maybe still break it down by chapter, with a list of issues under each chapter.  Obviously this is more work, but I think it would really help.  I'll see if I can get started on breaking this out today.

As far as completeness, my approach has just been to provide one or two important translations for each concept and not focus so much on have 100% coverage.  Long term, the more examples the better.  I even think there is potential to expand some of the examples or provide alternate ways of doing things (EG: here's the direct translation + here is maybe a better way to do the same thing).

I also need to figure out the setup so maybe others can edit directly edit from gitbook if they prefer that.  The markdown isn't horrible to figure out, but it would be nice to have.

PS: Thanks for jumping in!  I'm a newbie so it will be very helpful having someone more experience helping out.  I'll make sure to create a dedicated contributors section at some point.

**Comment by cdimitroulas** [comment]
Awesome, sounds good :)

>PS: Thanks for jumping in! I'm a newbie so it will be very helpful having someone more experience helping out. I'll make sure to create a dedicated contributors section at some point.

We're all just figuring things out :smile: happy to help fp-ts reach a wider audience!

**Comment by ChuckJonas** [comment]
#7 

Started breaking things out.  Lots of issues to still create, but hopefully this should help keep things organized.   I also added labels for each chapter
