### ISSUE TITLE
Prop function

### ISSUE THREAD

**Issue by cdimitroulas** [ChuckJonas/mostly-adequate-fp-ts#6]
In chapter 6 you mention that there is no `prop` function provided by fp-ts and then go on to define one yourself.

I don't know whether it's interesting, but I actually wrote an article a while ago about defining a type-safe `prop` function in Typescript which you can find here:
https://dev.to/cdimitroulas/writing-a-type-safe-prop-function-in-typescript-8d6

We could maybe include this definition instead of yours, although I'm conscious that it's more complicated to follow due to the types. The syntax in that blog post is also a little outdated. Here's a more "modern" version of the same function type signature:
https://www.typescriptlang.org/play?jsx=0&ts=4.1.5#code/MYewdgzgLgBADgJxHGBeGAeACgQygCxgFMAPKIsAEwhmgQEswBzAPgAoAoGb+PfALhi4CHAJRoWmAGo4ANgFciAGhgAlItHZceIAEYArQetAJK2PipkKikgGRqNUMYKuKJMPfoDacPgF0Abg4OAHoQmAAJEBAEHABPAEIYABV8ehowEAB3GFAAWzh6WQ1cmIQiYChZOI5QSFgALzR4JDg2ACIANzlFdtE2AG9aEDyiAkYmQQAGFW7rQSgENwBfUQCYMJgGwV1o4pwwIA

I'm wondering whether such a function would be useful in `fp-ts` actually :thinking: I'll ask the author about it!

**Comment by cdimitroulas** [comment]
`prop` function in `fp-ts` coming up :smile: https://github.com/gcanti/fp-ts/pull/1454

**Comment by ChuckJonas** [comment]
I also just came across [Record.lookup](https://gcanti.github.io/fp-ts/modules/Record.ts.html#lookup), which seems pretty similar to `safeProp`

**Comment by cdimitroulas** [comment]
Yep, `Record.lookup` is exactly the same as `safeProp` - it safely accesses a key and returns a `Maybe` (or `Option` in fp-ts, but it's the same thing!)

**Comment by ChuckJonas** [comment]
as we learned, `Record.lookup` is not really the same as `safeProp` as it doesn't returned the type for the indexed prop (but instead returns a union of all value types)

```
const safeValueProp = R.lookup('value');

const y = {value: true, foo: number}

const v = safeValueProp(y) //  O.Option<boolean | NumberC>
```
