### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by ChuckJonas** [ChuckJonas/mostly-adequate-fp-ts#8]
Translate one or more example to provide coverage of the concepts introduced in [asynchronous-tasks](https://mostly-adequate.gitbook.io/mostly-adequate-guide/ch08#asynchronous-tasks)

The "blog" application might be the best one:
```js
// getJSON :: String -> {} -> Task Error JSON
const getJSON = curry((url, params) => new Task((reject, result) => {
  $.getJSON(url, params, result).fail(reject);
}));

getJSON('/video', { id: 10 }).map(prop('title'));
// Task('Family Matters ep 15')

// -- Pure application -------------------------------------------------
// blogPage :: Posts -> HTML
const blogPage = Handlebars.compile(blogTemplate);

// renderPage :: Posts -> HTML
const renderPage = compose(blogPage, sortBy(prop('date')));

// blog :: Params -> Task Error HTML
const blog = compose(map(renderPage), getJSON('/posts'));


// -- Impure calling code ----------------------------------------------
blog({}).fork(
  error => $('#error').html(error.message),
  page => $('#main').html(page),
);

$('#spinner').show();
```

**Comment by ChuckJonas** [comment]
Made a [first attempt at this](https://github.com/ChuckJonas/mostly-adequate-fp-ts/blob/master/chapter-08-tupperware.md#task)... Pretty sure I did this wrong.  I think there are some fundamental differences between the book and `fp-ts` usage of "Task".  I think I instead need to use `TaskEither`.

Here's my attempt in a code sandbox https://codesandbox.io/s/fp-ts-ch8-task-h1bf7?file=/src/index.ts

**Comment by cdimitroulas** [comment]
@ChuckJonas yes you're right, `Task` is for an async operation which cannot fail, whereas `TaskEither` is for one which can fail/succeed. So to implement the example from the book you would need to use `TaskEither`.

I took a look at what you did and it looks correct :) There are some small simplifications/improvements that we can make to the code though. For example, the type-annotations on `resolve`/`reject` in the Promise are unnecessary. Here's what I got to compile in the Typescript playground:
```ts
import * as $ from "jquery";
import { pipe, flow } from "fp-ts/function";
import * as TE from "fp-ts/TaskEither";
import * as T from "fp-ts/Task";

type Video = { title: string };

const getJSON = <T>(url: string) => (params: Record<string, any>) =>
  TE.tryCatch(
    () =>
      new Promise<T>((resolve, reject) => {
        $.getJSON(url, params, resolve).fail((e) =>
          reject(new Error(e.statusText))
        );
      }),
    (reason) => new Error(String(reason))
  );

pipe(
  { id: 10 },
  getJSON<Video>("/video"),
  TE.map(video => video.title)
);
```

**Comment by ChuckJonas** [comment]
Changes incorporated.  Thanks!
